AWSTemplateFormatVersion: '2010-09-09'
Description: This is a Sample Template to Create EC2 Server
Parameters:
  SourceIP:
    Description: Source IP for Ingress Access
    Type: String
    MinLength: 9
    MaxLength: 18
    ConstraintDescription: Should be in Format valid CIDR like x.x.x.x/x
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})\/(\d{1,2})
  KeyName:
    Description: Display Existing in respective Region
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Should be a Valid Key Pair Name
Resources:
  EC2Server:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0483d54f340de0977
      InstanceType: t2.micro
      KeyName: 
        Ref: KeyName
      SecurityGroups:
        - Ref: SecurityGroup
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Open for HTTPS & SSH using CFT"
      SecurityGroupIngress:
      - CidrIp: !Ref SourceIP
        FromPort: 80
        ToPort: 80
        IpProtocol: tcp
      - CidrIp: !Ref SourceIP
        FromPort: 22
        ToPort: 22
        IpProtocol: tcp